__author__ = 'andra'

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__))+"/../ProteinBoxBot_Core")
import requests
import PBB_Core
import PBB_login
import PBB_settings
import traceback

import requests

if len(sys.argv) == 1:
    print("logfiles generated by PBB_Core as input")
    print("Example: python roleback_fullrun.py ~/bot/logs/WD_bot_run-2016-01-12_13:31.log")
    sys.exit()
else:
    try:
        login = PBB_login.WDLogin(PBB_settings.getWikiDataUser(), PBB_settings.getWikiDataPassword())
        cookies = login.get_edit_cookie()
        edit_token = login.get_edit_token()

        count = 0
        #logfile = open('/tmp/WD_bot_run-2016-01-12_13:31.log', 'r')
        logfile = open(sys.argv[1])
        for line in logfile.readlines():
            fields = line.split(",")
            if fields[0] != "ERROR":
                wdid = fields[5].strip()

                if wdid != "None":
                    headers = {
                        'content-type': 'application/x-www-form-urlencoded',
                        'charset': 'utf-8'
                    }
                    params = {
                                'action': 'wbgetentities',
                                'ids': wdid,
                                'format': 'json'
                    }
                    reply = requests.post(url="https://www.wikidata.org/w/api.php", data=params, headers=headers)
                    revid = wdoutput['entities'][wdid]['lastrevid']
                    print(wdid, revid)

                    headers = {
                        'content-type': 'application/x-www-form-urlencoded',
                        'charset': 'utf-8'
                    }
                    params = {
                                'action': 'edit',
                                'title': wdid,
                                'undo': revid,
                                'format': 'json',
                                'token': edit_token
                    }
                    reply = requests.post(url="https://www.wikidata.org/w/api.php", data=params, headers=headers, cookies=cookies)
                    print(reply.text)
    except (Exception):
        print(traceback.format_exc())
            
